import { act, cleanup, fireEvent, render, screen } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import HoldToDrawButton, { HOLD_TO_DRAW_MS } from "../HoldToDrawButton";

describe("HoldToDrawButton", () => {
  beforeEach(() => {
    vi.useFakeTimers();
  });

  afterEach(() => {
    cleanup();
    vi.useRealTimers();
  });

  function renderButton(props = {}) {
    const onHoldComplete = vi.fn();
    const onKeyboardActivate = vi.fn();
    render(
      <HoldToDrawButton
        onHoldComplete={onHoldComplete}
        onKeyboardActivate={onKeyboardActivate}
        {...props}
      />
    );
    return {
      onHoldComplete,
      onKeyboardActivate,
      button: screen.getByRole("button", { name: /draw movie/i }),
    };
  }

  it("fires onHoldComplete after a full hold", () => {
    const { button, onHoldComplete, onKeyboardActivate } = renderButton();

    fireEvent.pointerDown(button);
    act(() => {
      vi.advanceTimersByTime(HOLD_TO_DRAW_MS);
    });

    expect(onHoldComplete).toHaveBeenCalledTimes(1);
    expect(onKeyboardActivate).not.toHaveBeenCalled();
  });

  it("cancels when the pointer is released early", () => {
    const { button, onHoldComplete } = renderButton();

    fireEvent.pointerDown(button);
    act(() => {
      vi.advanceTimersByTime(HOLD_TO_DRAW_MS - 1);
    });
    fireEvent.pointerUp(button);
    act(() => {
      vi.advanceTimersByTime(HOLD_TO_DRAW_MS);
    });

    expect(onHoldComplete).not.toHaveBeenCalled();
  });

  it("cancels when the pointer leaves the button", () => {
    const { button, onHoldComplete } = renderButton();

    fireEvent.pointerDown(button);
    fireEvent.pointerLeave(button);
    act(() => {
      vi.advanceTimersByTime(HOLD_TO_DRAW_MS);
    });

    expect(onHoldComplete).not.toHaveBeenCalled();
  });

  it("ignores holds started with a secondary mouse button", () => {
    const { button, onHoldComplete } = renderButton();

    // jsdom drops `button` from synthesized pointer events, so build the
    // event by hand to actually carry the secondary-button flag.
    fireEvent(button, new MouseEvent("pointerdown", { bubbles: true, button: 2 }));
    act(() => {
      vi.advanceTimersByTime(HOLD_TO_DRAW_MS);
    });

    expect(onHoldComplete).not.toHaveBeenCalled();
  });

  // Keyboard and assistive-tech activation arrives as a click with detail 0;
  // pointer-release clicks carry detail >= 1 and must not double-trigger.
  it("routes keyboard activation to onKeyboardActivate", () => {
    const { button, onHoldComplete, onKeyboardActivate } = renderButton();

    fireEvent.click(button, { detail: 0 });

    expect(onKeyboardActivate).toHaveBeenCalledTimes(1);
    expect(onHoldComplete).not.toHaveBeenCalled();
  });

  it("ignores the click generated by a pointer release", () => {
    const { button, onKeyboardActivate } = renderButton();

    fireEvent.click(button, { detail: 1 });

    expect(onKeyboardActivate).not.toHaveBeenCalled();
  });

  it("does nothing while disabled", () => {
    const { button, onHoldComplete, onKeyboardActivate } = renderButton({ disabled: true });

    expect(button).toBeDisabled();
    fireEvent.pointerDown(button);
    act(() => {
      vi.advanceTimersByTime(HOLD_TO_DRAW_MS);
    });
    fireEvent.click(button, { detail: 0 });

    expect(onHoldComplete).not.toHaveBeenCalled();
    expect(onKeyboardActivate).not.toHaveBeenCalled();
  });

  it("does not start a hold while a draw is in flight", () => {
    const onHoldComplete = vi.fn();
    render(<HoldToDrawButton onHoldComplete={onHoldComplete} isLoading />);

    const button = screen.getByRole("button", { name: /drawing movie from bowl/i });
    fireEvent.pointerDown(button);
    act(() => {
      vi.advanceTimersByTime(HOLD_TO_DRAW_MS);
    });

    expect(onHoldComplete).not.toHaveBeenCalled();
  });
});
