// Generated by scripts/refresh-provider-logos.mjs on 2026-09-04.
// Do not edit by hand.
//
// TMDB's API terms cap caching their content at six months, so re-run the
// script before this date is that old. A service missing from the map renders
// as its name, which is what every one of them did before logos existed.
const PROVIDER_LOGO_PATHS = {
  "Netflix": "/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg",
  "Hulu": "/bxBlRPEPpMVDc4jMhSrTf2339DW.jpg",
  "Disney+": "/97yvRBw1GzX7fXprcF80er19ot.jpg",
  "Prime Video": "/pvske1MyAoymrs5bguRfVqYiM9a.jpg",
  "Max": "/jbe4gVSfRlbPTdESXhEKpornsfu.jpg",
  "Apple TV+": "/mcbz1LgtErU9p4UdbZ0rG6RTWHX.jpg",
  "Paramount+": "/fts6X10Jn4QT0X6ac3udKEn2tJA.jpg",
  "Peacock": "/2aGrp1xw3qhwCYvNGAJZPdjfeeX.jpg",
  "Crunchyroll": "/fzN5Jok5Ig1eJ7gyNGoMhnLSCfh.jpg",
  "AMC+": "/ovmu6uot1XVvsemM2dDySXLiX57.jpg",
  "Starz": "/yIKwylTLP1u8gl84Is7FItpYLGL.jpg",
  "MUBI": "/x570VpH2C9EKDf1riP83rYc5dnL.jpg",
  "The Criterion Channel": "/yhrtzYd43pFIhRq0ruO8umJPuyn.jpg",
  "Tubi": "/zLYr7OPvpskMA4S79E3vlCi71iC.jpg",
  "Pluto TV": "/dB8G41Q6tSL5NBisrIeqByfepBc.jpg",
  "The Roku Channel": "/wQzSN83BnWVgO7xEh0SeTVqtrFv.jpg",
  "Kanopy": "/rcBwnERpNfPfWB5DaSTyEMCZbCA.jpg",
};

export function getServiceLogoPath(serviceName) {
  return PROVIDER_LOGO_PATHS[serviceName] || null;
}
